# Generated by Django 3.2.5 on 2021-07-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_news_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
            ],
        ),
    ]
